# Generated by Django 5.1.7 on 2025-04-06 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_info', '0005_alter_activity_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
