# Generated by Django 5.1.7 on 2025-04-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_info', '0007_alter_activity_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='created_by',
            new_name='created_by_user',
        ),
    ]
