# Generated by Django 5.1.7 on 2025-04-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_info', '0003_user_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='activity',
            name='files',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='urgency',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('moderate', 'Moderate'), ('doLater', 'DoLater')], default='moderate', max_length=40),
        ),
    ]
