# Generated by Django 5.2 on 2025-04-08 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_info', '0009_activity_general_task_activity_gnrl_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='assin_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='get_info.user'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='urgency',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('moderate', 'Moderate'), ('doLater', 'DoLater'), ('general', 'General')], default='moderate', max_length=40),
        ),
    ]
