# Generated by Django 5.1.7 on 2025-04-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_info', '0004_delete_task_activity_files_activity_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
    ]
