# Generated by Django 5.1.1 on 2025-04-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_info', '0010_alter_activity_assin_to_alter_activity_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
