# Generated by Django 5.1.1 on 2025-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_info', '0011_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='task_des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
